#!/bin/bash
 
set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py migrate_schemas
python3 /app/manage.py collectstatic --no-input

/usr/local/bin/gunicorn spy_agency.wsgi --bind 0.0.0.0:1998 --chdir=/app