# Generated by Django 4.1.2 on 2022-11-29 06:17

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("system_hits", "0003_alter_hit_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hit",
            name="state",
            field=django_fsm.FSMField(default="Assigned", max_length=50),
        ),
    ]
