# Generated by Django 4.1.2 on 2022-11-29 06:17

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=django_fsm.FSMField(default="Active", max_length=50),
        ),
    ]
